version: '3.3'

services:
  nextjs:
    ports:
      - 4000:3000
    build:
      context: .
      dockerfile: ./docker/local.dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  nestjs:
    ports:
      - 9001:3000
    build:
      context: ./backend
      dockerfile: ./dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
